title: Budget Haver
email: talk@pdyxs.wtf
description: "A website for Budget Haver: a budgeting app"
url: https://budgethaver.app # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
